---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]

verifier:
  name: inspec

provisioner:
  name: chef_zero
  data_path: test/shared
  attributes:
    apache:
      default_site_enabled: false
      config:
        auth:
          registerEmailPrivateKey: 123123123
          restTokenPrivateKey: 123123123

platforms:
  - name: debian-7.8
    attributes:
      apt:
        compile_time_update: true
    run_list:
      - recipe[apt::default]
      - recipe[gerrit_test::wget]
  - name: debian-8.5
    attributes:
      apt:
        compile_time_update: true
    run_list:
      - recipe[apt::default]
      - recipe[gerrit_test::wget]

suites:
  - name: DB-H2
    run_list:
      - recipe[gerrit::default]
    excludes: ["ubuntu-13.10"]
  - name: DB-MYSQL
    run_list:
      - recipe[gerrit::default]
    attributes:
      gerrit:
        config:
          database:
            type: MYSQL
      mysql:
        server_debian_password: "foo"
        server_root_password: "foo"
        server_repl_password: "foo"
  - name: DB-POSTGRESQL
    run_list:
      - recipe[gerrit::default]
    attributes:
      gerrit:
        database:
          type: POSTGRESQL
      postgresql:
        password:
          postgres: "foo"
  - name: PROXY-NONE
    run_list:
      - recipe[gerrit::default]
    attributes:
      gerrit:
        proxy:
          enable: false
